### ISSUE TITLE
Docker host container does not get removed upon reset.

### ISSUE THREAD

**Issue by PodTheCoder** [PodTheCoder/edge_staking_gui#5]
# Explanation
Currently, pressing "Back To Setup" only stops the Docker host container via the Edge CLI command `edge stop`.
However, the host container auto restarts when Docker is launched.
This can cause a scenario where the user changes their device code, but still runs it using the old configuration.

# Solution
Ideally, the device would be removed from the network instead of stopped. However, this gives the error "wallet not found."

**Comment by annybs** [comment]
This is probably because the Host container is [created](https://docs.docker.com/engine/api/v1.41/#tag/Container/operation/ContainerCreate) with a `.HostConfig.RestartPolicy` of `"always"` so that whenever Docker restarts, the container starts up again with it.

If the container is removed, then it won't start back up. If GUI is interfacing with `edge` CLI then it [should](https://github.com/edge/cli/blob/f71951a34144313b1e1500dfc9d0b7963c765b11/src/device/cli/stop.ts#L38-L39) be removed.

I don't have an actual answer for you, just thought it might be useful context.

**Comment by PodTheCoder** [comment]
Good to know the container is automatically removed upon running stop! That makes the fix easier. 
I'll make sure the stop command is ran before starting the node.

I also realized the bug can pop up in multiple situations:
1. When setting up the node. (The user could create & display a device code, start the node, create & display a device code, and start the node again.)
2. When pressing `Back to Setup`. (The node can already be running via autostart or by manually pressing the `Start Node` button.)
3. When switching the network. (The node can already be running on the other network.)

**Comment by PodTheCoder** [comment]
Fixed in https://github.com/PodTheCoder/edge_staking_gui/commit/ef25e7f1b64344562affd457e73bb9ac2dfd335d & https://github.com/PodTheCoder/edge_staking_gui/commit/97c2d9ba23994787eef0b98d1d508363f0fa4dde
